version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080/api

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./backend/storage/files:/app/storage/files  # Monta la carpeta local de archivos al contenedor
    networks:
      - app-network

  # Servicio para esperar que el backend esté listo antes de iniciar el frontend
  wait-for-it:
    image: busybox
    command: /bin/sh -c "until nc -z backend 8080; do sleep 1; done;"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
