version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
      - ./backend/vendor:/var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_KEY=base64:xxxxxxxxxxxxxxxx
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0 # Actualizado a una versión más reciente
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install &&
             npm run serve"
    depends_on:
      - backend

volumes:
  db_data:
